apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/agent-sandbox//k8s?ref=f9cf22a0936390a120353380fed80392278de6b6
  - ../platform

images:
  - name: ko://sigs.k8s.io/agent-sandbox/cmd/agent-sandbox-controller
    newName: registry.k8s.io/agent-sandbox/agent-sandbox-controller
    digest: sha256:ba381b4e0c86cca597d5c5a31860e38d30ec1c45e0a7a8328bb2799c87d059c0

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: agent-sandbox-controller
      namespace: agent-sandbox-system
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext
        value:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      - op: add
        path: /spec/template/spec/containers/0/securityContext
        value:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
