apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - controller-config.yaml
  - serviceaccounts.yaml
  - router.yaml
  - router-rbac.yaml
  - network-policies.yaml
