apiVersion: v1
kind: Namespace
metadata:
  name: sandherd-system
  labels:
    app.kubernetes.io/part-of: sandherd
    sandherd.dev/router-clients: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
