apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: extensions.agents.x-k8s.io
      version: v1beta1
      kind: SandboxTemplate
      name: sandherd-smoke
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: rook-ceph-block
